---
title: "Section 2: Scatter plots of nail vs serum measures"
output:
  pdf_document:
    number_sections: yes
    toc: no
    highlight: tango
  html_document:
    theme: united
    toc: no
editor_options:
  chunk_output_type: console
header-includes:
 \usepackage{float}
---


```{r, include=FALSE}

knitr::opts_chunk$set(echo = F, 
                      results = 'hide',
                      fig.keep="all",
                      warning = F,
                      fig.pos = 'H',
                      fig.width=10,
                      fig.height=6,
                      message=F,
                      float=F)

#runif(1, 0, 10^8)
set.seed(74268794)

```


```{r, include=F}
# bring in packages
require(knitr)
require(haven)
require(data.table)
require(ggplot2)
require(kableExtra)
require(labelled)
library(dplyr)
library(tidyr)
library(plyr)
library(grid)
require(boot)
```


```{r, results='hide'}

# source: data-handling-cch.Rmd
load(file="../sections/updated-data-iron.RData") # sub.dat is subset, all.dat is total data

nail.names2
iron.names2
serum.names2


# NOTE: have to run section5-spearman.Rmd first 
load(file="pca-info.RData") # pca.log, loading.matrix, pc.info

dim(sub.dat)
sub.dat = merge(sub.dat, pc.info, by="PSID", all.x=T)
dim(sub.dat)
summary(sub.dat[c("PC1", "PC1.scl")])
```

```{r}

# What is the overlap between UMN and RTI sample?
# ==============================================
table(sub.dat$subcohort)
summary(sub.dat$RTI_Toenail_fe)

table(!(is.na(sub.dat[sub.dat$subcohort==1,]$RTI_Toenail_fe)), !(is.na(sub.dat[sub.dat$subcohort==1,]$UMN_Iron)))
# there are 118 RTI measures in the umn subcohort sample

table(!is.na(all.dat$RTI_Toenail_fe)) # 2996 rti fe at baseline


# from frequencies.Rmd
load( file="ids-include-basefu.RData") # baseline.all.id, fu.all.id, base.fu.all.id


# from data-handling-cch.Rmd
load(file="ids-include.RData") # psid.include, psid.include2


all.dat$baseline.umn = ifelse(all.dat$PSID %in% baseline.all.id, 1, 0)

with(all.dat[all.dat$UMN_Iron==1,], table(!(is.na(RTI_Toenail_fe)), baseline.umn)) # 1,341 non-missing RTI samples in the UMN serum samples


table(!is.na(all.dat$RTI_Toenail_fe)) # 2996 non-missing rti nail fe values

all.dat2 = all.dat[!is.na(all.dat$RTI_Toenail_fe_Adj) & all.dat$PSID %in% psid.include2,]
table(all.dat2$subcohort) 
dim(all.dat2)

with(all.dat2,
     table(baseline.umn)) # number in rti fe nail values in the umn case-cohort sample described in data-handling-cch.Rmd, 4 are in the subcohort sample we are using (with both umn and Dartmouth nail values)


summary(all.dat$RTI_Toenail_fe_Adj)
table(all.dat$baseline.umn) # number of values in baseline umn data with dartmouth nail samples that are in subcohort

save(all.dat2, file="RTI-dat.RData") # use this RTI data set for subsequent analyses

summary(all.dat2$RTI_Toenail_fe_Adj) # Toenail Metals Case-Cohort: Iron measurement, ug/g, adjusted for batch (RTI)

summary(all.dat2$RTI_Toenail_fe)
dim(all.dat2)

nrow(all.dat2[!(is.na(all.dat2$RTI_Toenail_fe_Adj)),])
nrow(all.dat2[!(is.na(all.dat2$UMN_Iron_Baseline_FE)),])
nrow(all.dat2[!(is.na(all.dat2$UMN_Iron_Baseline_FERTN)),])
nrow(all.dat2[!(is.na(all.dat2$UMN_Iron_Baseline_FESAT)),])

# double check that there is at least one pair of rti toenail and serum measures for the 1,330

check1 = with(all.dat2, table(!(is.na(all.dat2$RTI_Toenail_fe_Adj)), 
                     !(is.na(all.dat2$UMN_Iron_Baseline_FE)),
                     !(is.na(all.dat2$UMN_Iron_Baseline_FERTN)),
                     !(is.na(all.dat2$UMN_Iron_Baseline_FESAT))))
test.counts = as.data.frame(check1)
sum(test.counts$Freq)
names(test.counts) = c("Toenail", "Serum Iron", "Serum Ferritin", "Transferrin Saturation", "Freq")

# how many people from baseline primary sample with both UMN serum and Dartmouth nails are also in RTI sample?

length(baseline.all.id[baseline.all.id %in% all.dat2$PSID]) # 4 people

names(all.dat2)
summary(all.dat2$DR224_SCL_Serum_Draw_Year) # 2013-2015
summary(all.dat2$DR224_Serum_Draw_Year)     # 2003-2009


names(all.dat2)[grepl("Year", names(all.dat2))]
names(all.dat2)[grepl("Draw", names(all.dat2))]

```

```{r, results='markup'}

kable(test.counts,
      caption="Number of non-missing values by RTI toenail and serum values.",
      booktabs=T)

# 1,240 with all values, 10 with toenail, ferritin and fesat, 72 with toenail, fe and ferritin, 8 with toenail, ferritin and fesat.
```

```{r}

# Make long style data frame for 4 panel plot

# Create data with rti sample that has UMN serum values in case and case-cohort

dat.long. <- 
  all.dat2 %>% 
  dplyr::select(c(UMN_Iron_Baseline_FE, UMN_Iron_Baseline_FERTN, UMN_Iron_Baseline_FESAT, 
                  subcohort.nocases,
                  PSID)) %>% 
  pivot_longer(cols = -c("PSID", 'subcohort.nocases'),
               values_drop_na=T)


dat.long = merge(dat.long., all.dat2[complete.cases(all.dat2$RTI_Toenail_fe_Adj),
                                                   c("PSID", "RTI_Toenail_fe_Adj")], 
                 by="PSID",
                 all.y=T)

levels(factor(dat.long$name))

dat.long = within(dat.long, {
  no.case = factor(subcohort.nocases,
                   labels=c("No", "Yes"))
  name.f = factor(name, labels=c("Iron", "Ferritin", "Transferrin Saturation"))
})

colnames(dat.long)[which(colnames(dat.long) %in% "RTI_Toenail_fe_Adj")]="Nail"

head(dat.long)
dim(dat.long)
length(unique(dat.long$PSID))

```


# Scatter plots # {#scatter}

## Baseline

### Untransformed with outliers

```{r}

deming.r = function(df){
  x=df$Nail
  y=df$value 
  pca <- prcomp(~x+y, df)
  slp <- with(pca, rotation[2,1] / rotation[1,1])
  int <- with(pca, center[2] - slp*center[1])
  return(c(int=int,slp=slp))
}

# Source: https://stackoverflow.com/questions/1169539/linear-regression-and-group-by-in-r
# Break up data frame by iron measure, then fit the specified model to each piece and
# return a list

models <- dlply(dat.long, "name.f", deming.r)
# return a data frame
model.info=ldply(models); model.info

#merge line info onto plot data
dat.long1 = merge(dat.long, model.info, by="name.f")
head(dat.long1)

ggplot(dat.long1, aes(Nail, value, colour=no.case)) + 
  geom_point() + 
  stat_smooth(method=lm, color="green", se=FALSE) +
  facet_wrap(.~name.f,scales = "free")+
  geom_abline(aes(slope=slp, intercept=int.y), color="blue") +
  labs(x="Toenail (mcg/g)", 
       y="Serum (mcg/dL)") +
  scale_colour_manual(values = c("grey", "black"),
                      name="Case status") +
  theme_bw()

```


### Untransformed without outliers

#### Information on outlier

```{r}
  
extreme.id = sub.dat[which(sub.dat$RTI_Toenail_fe_Adj > quantile(sub.dat$RTI_Toenail_fe_Adj, 0.998, na.rm=T)),]$PSID # remove people with fe values greater than 0.002 quantile, top 0.2%

extreme.id
sub.dat[sub.dat$PSID %in% c(extreme.id),]$RTI_Toenail_fe_Adj
summary(sub.dat$RTI_Toenail_fe_Adj)
summary(sub.dat$RTI_Toenail_fe_Adj)

```

#### Plot

```{r}

#dim(sub.dat)
dat.long1 = dat.long1[!(dat.long1$PSID %in% extreme.id),]
#dim(sub.dat1)

# get Deming regression info
models1 <- dlply(dat.long1, "name.f", deming.r)
# return a data frame
model.info1=ldply(models1); model.info1
names(model.info1) = c("name.f", "int.1", "slp.1")
#merge line info onto plot data
dat.long2 = merge(dat.long1, model.info1, by="name.f")
head(dat.long2)


p1 = ggplot(dat.long2, aes(Nail, value, colour=no.case)) + 
  geom_point() + 
  stat_smooth(method=lm, color="green", se=FALSE) +
  facet_wrap(.~name.f)+
  geom_abline(aes(slope=slp.1, intercept=int.1), color="blue") +
  labs(x="Toenail (mcg/g)", 
       y="Serum (mcg/dL)") +
  scale_colour_manual(values = c("grey", "black"),
                      name="Case status") +
  theme_bw()

p1
```


### log transformed without outliers

```{r}

deming.r.log = function(df){
  x=log(df$Nail)
  if(df$name.f[1]=="PC1") y=df$value else y=log(df$value)
  pca <- prcomp(~x+y, df)
  slp <- with(pca, rotation[2,1] / rotation[1,1])
  int <- with(pca, center[2] - slp*center[1])
  
  ols.m = lm(y~x)
  return(c(int=int,slp=slp, int.ols=coef(ols.m)[1], slp.ols=coef(ols.m)[2]))
}

# get Deming regression info
models2 <- dlply(dat.long1, "name.f", deming.r.log)
# return a data frame
model.info2=ldply(models2); model.info2
names(model.info2) = c("name.f", "int.2", "slp.2", "int.ols", "slp.ols")
#merge line info onto plot data
dat.long3 = merge(dat.long2, model.info2, by="name.f")
head(dat.long3)


p1 = ggplot(dat.long3, aes(log(Nail), log(value), colour=no.case)) + 
  geom_point() + 
  stat_smooth(method=lm, color="green", se=FALSE) +
  facet_wrap(.~name.f, scales = "free", ncol=4)+
  geom_abline(aes(slope=slp.2, intercept=int.2), color="blue") +
  # geom_text(aes(2, 2, label = paste(#"Adj R2 = ", adj.r.squared, "\n",
  #                                  "Deming regression \n",
  #                                  "Intercept =", round(int.2,2), "\n",
  #                                  "Slope =", round(slp.2,2), "\n"#,
  #                                  #"P =", pvalue
  #                                  )), color="blue") +
  # geom_text(aes(4, 2, label = paste(#"Adj R2 = ", adj.r.squared, "\n",
  #                                  "OLS regression \n",
  #                                  "Intercept =", round(int.ols,2), "\n",
  #                                  "Slope =", round(slp.ols,2), "\n"#,
  #                                  #"P =", pvalue
  #                                  )), color="green") +
  labs(x="ln(Toenail (mcg/g))", 
       y="ln(Serum (mcg/dL))") +
  scale_colour_manual(values = c("grey", "black"),
                      name="Case status") +
  theme_bw() +
  theme(legend.position = "bottom") +
  labs(caption = "Note: Green line is OLS fit and blue line is Deming regression")
  

p1


```

```{r, eval=F, include=F}
# Look at prediction intervals for one outcome

#create simple linear regression model
table(dat.long3$name.f)
summary(dat.long3$value)

# PC1 
dat.pc =  dat.long3[which(dat.long3$name.f=="PC1"),]
model.pc1 <- lm(value ~ Nail, data = dat.pc)

# Use model to create prediction intervals
predictions <- predict(model.pc1, interval = "predict")

dat.pcp = cbind(dat.pc, predictions)

p1.pred = ggplot(dat.pcp, aes(Nail, value, colour=no.case)) + 
  geom_point() + 
  stat_smooth(method=lm, color="green", se=FALSE) +
  labs(x="Toenail (mcg/g)", 
       y="Serum (mcg/dL)") +
  scale_colour_manual(values = c("grey", "black"),
                      name="Case status") +
  theme_bw() +
  xlim(0,50) +
  theme(legend.position = "bottom") +
  labs(caption = "Note: Green line is OLS fit and blue line is Deming regression") +
  geom_line(aes(y = lwr), col = "coral2", linetype = "dashed") + #lwr pred interval
  geom_line(aes(y = upr), col = "coral2", linetype = "dashed") + #upr pred interval
  facet_wrap(.~name.f, scales = "free", nrow=4)

p1.pred

```

```{r,fig.width=6, fig.height=10}
# now loop through all 4 values with a function to get plots with prediction intervals

# function to get data set with prediction intervals
get.pred <- function(df){
  model1 <- lm(value ~ Nail, data = df)
  # Use model to create prediction intervals
  predictions <- predict(model1, interval = "predict")
  dat.p = cbind(df, predictions)
  return(dat.p)
}

# get prediction intervals by each of the four iron outcomes, fe, fertn, fesat and PC1
preds <- dlply(dat.long3, "name.f", get.pred)

# return a data frame
pred.df = ldply(preds)
#head(pred.df); dim(pred.df); dim(dat.long3)

# Plot prediction intervals with a linear regression line
p1.pred = ggplot(pred.df, aes(Nail, value, colour=no.case)) + 
  geom_point() + 
  stat_smooth(method=lm, color="green", se=T) +
  labs(x="Toenail (mcg/g)", 
       y="Serum (mcg/dL)") +
  scale_colour_manual(values = c("grey", "black"),
                      name="Case status") +
  theme_bw() +
  facet_wrap(.~name.f, scales = "free", nrow=4) +
#  xlim(0,50) +
  theme(legend.position = "bottom") +
  labs(caption = "Note: Green line is OLS fit and red dashed lines are prediction intervals") +
  geom_line(aes(y = lwr), col = "coral2", linetype = "dashed") + #lwr pred interval
  geom_line(aes(y = upr), col = "coral2", linetype = "dashed") #upr pred interval

p1.pred

```




<!-- re-do of poster after co-authors requests. -->



```{r, results='hide'}
# get Spearman with CI

# source: https://content.csbs.utah.edu/~rogers/datanal/labprj/bootstrap/index.html

ferritin = sub.dat[, c("UMN_Iron_Baseline_FERTN", "RTI_Toenail_fe_Adj")]
fe = sub.dat[, c("UMN_Iron_Baseline_FE", "RTI_Toenail_fe_Adj")]
fesat = sub.dat[, c("UMN_Iron_Baseline_FESAT", "RTI_Toenail_fe_Adj")]

dim(ferritin)
dim(fe)
dim(fesat)

# Spearman's correlation from observed data

# function to get correlation
getcor <- function(x, ndx) {
  dat1.cor = cor(x[ndx,1], x[ndx,2], method="spearman", use="complete.obs")
    return(dat1.cor)
}

# check
cor(fe, use="complete.obs")
getcor(ferritin)

# bootstrap spearman correlation for two time points
fe.boot <- boot(fe, getcor, R=1000, stype="i")
ferritin.boot <- boot(ferritin, getcor, R=1000, stype="i")
fesat.boot <- boot(fesat, getcor, R=1000, stype="i")


# function to get means and se
get.dat = function(dat, serum){
  

  mean = mean(dat$t)
  se = sd(dat$t); se # get sd of sampling dist = se
  
  uci = mean + 1.96*se; uci
  lci = mean - 1.96*se ; lci
  
  return(data.frame(serum=serum,
                    mean.serum=mean(dat$t), 
                    se.serum = sd(dat$t),
                    uci=uci, lci=lci))
}

dat.summary = rbind.data.frame( get.dat(fe.boot, "fe"),
                                get.dat(ferritin.boot, "ferritin"),
                                get.dat(fesat.boot, "transferrin saturation") )
dat.summary
```

```{r}

dat.summary = within(dat.summary, {
  name.f = ifelse(serum=="fe", "Iron",
                  ifelse(serum=="ferritin", "Ferritin",
                         ifelse(serum=="transferrin saturation", "Transferrin Saturation", NA)))
  x = log(c(exp(3.75), exp(4.8), exp(2.5)))
  y = log(rep(200-75,3))
  no.case = NA
  text = paste0("Spearman coef =\n",
                formatC(round(mean.serum, 2), format="f", digits=2),
                " (",
                round(lci, 2),
                ",",
                formatC(round(uci,2), format="f", digits=2), ")")
})

dat.summary

```



```{r}

table(pred.df$no.case)
table(pred.df$name.f)
iron_names <- c(
                    `Iron` = "Iron (mcg/dL)\n(n=1,321)",
                    `Ferritin` = "Ferritin (mcg/dL)\n(n=1,319)",
                    `Transferrin Saturation` = "Transferrin Saturation (%)\n(n=1249)"
                    )


# Plot pb regression lines with points

table(pred.df$name.f)
pred.df = pred.df[!(pred.df$name.f=="PC1"),]
table(pred.df$name.f)

pb.fig2.rti = ggplot(pred.df, aes(y=log(Nail), x=log(value))) + 
  geom_hex() +
  scale_fill_gradient(low="lightgray",high="black") +
  #  geom_point(size=3, alpha=0.25) + 
  labs(y="ln(Toenail (mcg/g))", 
       x="ln(Serum measure)") +
  theme_bw(base_size=30) +
  facet_wrap( . ~ name.f, nrow=1, labeller = as_labeller(iron_names)) + # scales = "free",
#  xlim(0,50) +
  theme(legend.position = "right") 
#  geom_abline(data=est.df, aes(intercept=int.pb, slope=slp.pb, colour="Passing-Bablock"), lwd=1.5) +
#  geom_abline(data=est.df, aes(intercept=int.ols, slope=slp.ols, colour="OLS"), lwd=1.5)  +
#  geom_abline(data=est.df, aes(intercept=int.int, slope=0, colour="Average"), lwd=1.5) +
#  geom_text(data=est.df, aes(x=x, y=y, label=text), size=5, color=cbb[3]) +
#  geom_abline(aes(intercept=0, slope=1, colour="Unity"), lwd=1.5) +
#  scale_shape_manual("Case", values=c(21,19))
#  geom_text(data=dat.summary, aes(x=x, y=y, label=text), size=7, color="black") 
  
pb.fig2.rti

```


```{r}

ggsave(file="pb-poster-RTI.png", width = 16, height = 6, device='png', dpi=700)

```


```{r, results='markup'}

kable(model.info2, booktabs=T)

```


```{r}

save(p1, pb.fig2.rti,  p1.pred,  model.info2, file="section2-RTI-plots.RData")

```

